//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soft_educational_APM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soft_educational_APM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&gt; sortează muchiile în ordine crescătoare a costurilor
        ///-&gt; include inițial fiecare nod într-o mulțime diferită
        ///-&gt; până când nu avem n-1 muchii in APCM
        ///	-&gt; extrage muchia de cost minim
        ///	-&gt; dacă (extremitățile muchiei extrase fac parte din mulțimi diferite) atunci
        ///		-&gt; muchia se adaugă în APCM
        ///		-&gt; și extremitățile se reunesc în aceeași mulțime
        ///	=&gt; sfârșit dacă &lt;=
        ///=&gt; sfârșit până când &lt;=.
        /// </summary>
        internal static string kruskalPseudo {
            get {
                return ResourceManager.GetString("kruskalPseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&gt; se consideră un nod de start care se marchează ca vizitat (celelalte noduri, inițial, sunt nevizitate)
        ///-&gt; se repetă de n-1 ori pașii :
        ///	-&gt; se consideră nodul nevizitat (NVmin) aflat la distanță minimă față de un nod deja vizitat (Vmin)
        ///	-&gt; muchia NVmin-Vmin se adaugă la arbore
        ///	-&gt; NVmin se consideră vizitat.
        /// </summary>
        internal static string primPseudo {
            get {
                return ResourceManager.GetString("primPseudo", resourceCulture);
            }
        }
    }
}
